spring.application.name=hospitalManagement

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api/v1

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# MySQL database connection URL, port, and database name
spring.datasource.url=jdbc:mysql://localhost:3306/hospitalDB

# Database username and password
spring.datasource.username=root
spring.datasource.password=manager

# MySQL driver class name (com.mysql.cj.jdbc.Driver is used in modern versions)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#security config
#spring.security.user.name=sanket
#spring.security.user.password=123